# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PestCalibrationUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/EPA1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_chooseObservationFile = QtWidgets.QLabel(self.centralwidget)
        self.label_chooseObservationFile.setGeometry(QtCore.QRect(100, 60, 351, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_chooseObservationFile.setFont(font)
        self.label_chooseObservationFile.setObjectName("label_chooseObservationFile")
        self.lineEdit_observationFile = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_observationFile.setGeometry(QtCore.QRect(100, 110, 380, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.lineEdit_observationFile.setFont(font)
        self.lineEdit_observationFile.setReadOnly(True)
        self.lineEdit_observationFile.setObjectName("lineEdit_observationFile")
        self.observationBrowse = QtWidgets.QPushButton(self.centralwidget)
        self.observationBrowse.setGeometry(QtCore.QRect(520, 110, 150, 41))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.observationBrowse.setFont(font)
        self.observationBrowse.setDefault(False)
        self.observationBrowse.setObjectName("observationBrowse")
        self.label_chooseObservationType = QtWidgets.QLabel(self.centralwidget)
        self.label_chooseObservationType.setGeometry(QtCore.QRect(100, 230, 351, 33))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_chooseObservationType.setFont(font)
        self.label_chooseObservationType.setObjectName("label_chooseObservationType")
        self.comboBox_ODT = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_ODT.setGeometry(QtCore.QRect(100, 280, 380, 41))
        self.comboBox_ODT.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.comboBox_ODT.setObjectName("comboBox_ODT")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.comboBox_ODT.addItem("")
        self.runCalibrationButton = QtWidgets.QPushButton(self.centralwidget)
        self.runCalibrationButton.setGeometry(QtCore.QRect(100, 400, 220, 47))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        self.runCalibrationButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Go.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.runCalibrationButton.setIcon(icon1)
        self.runCalibrationButton.setDefault(True)
        self.runCalibrationButton.setObjectName("runCalibrationButton")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 38))
        self.menubar.setObjectName("menubar")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Pest Calibration"))
        self.label_chooseObservationFile.setText(_translate("mainWindow", "Choose Observation Data File:"))
        self.observationBrowse.setText(_translate("mainWindow", "Browse..."))
        self.label_chooseObservationType.setText(_translate("mainWindow", "Choose Observation Data Type:"))
        self.comboBox_ODT.setItemText(0, _translate("mainWindow", "Total Evaporation(in/hr)"))
        self.comboBox_ODT.setItemText(1, _translate("mainWindow", "Surface Infiltration(in/hr)"))
        self.comboBox_ODT.setItemText(2, _translate("mainWindow", "Pavement Perc(in/hr)"))
        self.comboBox_ODT.setItemText(3, _translate("mainWindow", "Soil Perc(in/hr)"))
        self.comboBox_ODT.setItemText(4, _translate("mainWindow", "Storage Exfil(in/hr)"))
        self.comboBox_ODT.setItemText(5, _translate("mainWindow", "Surface Runoff(in/hr)"))
        self.comboBox_ODT.setItemText(6, _translate("mainWindow", "Drain Outflow(in/hr)"))
        self.comboBox_ODT.setItemText(7, _translate("mainWindow", "Surface Level(inches)"))
        self.comboBox_ODT.setItemText(8, _translate("mainWindow", "Pavement Level(inches)"))
        self.comboBox_ODT.setItemText(9, _translate("mainWindow", "Soil Moisture content"))
        self.comboBox_ODT.setItemText(10, _translate("mainWindow", "Storage Level (inches)"))
        self.runCalibrationButton.setText(_translate("mainWindow", "Run Calibration"))

